/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface DayPicker {}
  interface MonthPicker {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLDayPickerElement extends Components.DayPicker, HTMLStencilElement {}
  var HTMLDayPickerElement: {
    prototype: HTMLDayPickerElement;
    new (): HTMLDayPickerElement;
  };

  interface HTMLMonthPickerElement extends Components.MonthPicker, HTMLStencilElement {}
  var HTMLMonthPickerElement: {
    prototype: HTMLMonthPickerElement;
    new (): HTMLMonthPickerElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'day-picker': HTMLDayPickerElement;
    'month-picker': HTMLMonthPickerElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface DayPicker {}
  interface MonthPicker {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'day-picker': DayPicker;
    'month-picker': MonthPicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'day-picker': LocalJSX.DayPicker & JSXBase.HTMLAttributes<HTMLDayPickerElement>;
      'month-picker': LocalJSX.MonthPicker & JSXBase.HTMLAttributes<HTMLMonthPickerElement>;
    }
  }
}


