/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface StTimepicker {
    'class': string;
    'clock24': boolean;
    'label': string;
    'name': string;
    'selected': string;
    'step': number;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLStTimepickerElement extends Components.StTimepicker, HTMLStencilElement {}
  var HTMLStTimepickerElement: {
    prototype: HTMLStTimepickerElement;
    new (): HTMLStTimepickerElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'st-timepicker': HTMLStTimepickerElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppRoot {}
  interface StTimepicker {
    'class'?: string;
    'clock24'?: boolean;
    'label'?: string;
    'name'?: string;
    'selected'?: string;
    'step'?: number;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'st-timepicker': StTimepicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'st-timepicker': LocalJSX.StTimepicker & JSXBase.HTMLAttributes<HTMLStTimepickerElement>;
    }
  }
}


